### ISSUE TITLE
Publish at PyPI?

### ISSUE THREAD

**Issue by bebraw** [maranas/pyNotificationCenter#1]
Hi,

Could you consider publishing this library at [PyPI](http://pypi.python.org/pypi)?

**Comment by ghickman** [comment]
This would be really useful. If you'd like I can make a pull request with a `setup.py`?

**Comment by sylg** [comment]
That would be awesome!

On 26 sept. 2012, at 17:06, George Hickman notifications@github.com wrote:

This would be really useful. If you'd like I can make a pull request with a
setup.py?

—
Reply to this email directly or view it on
GitHubhttps://github.com/maranas/pyNotificationCenter/issues/1#issuecomment-8893077.

**Comment by maranas** [comment]
@ghickman sorry, didn't notice my notifications. Sure, just do a pull request and I'll merge it as soon as I receive it.

**Comment by rodrigoaraujo01** [comment]
Joining the chorus, it'd be really great.

I had some problems installing pyobjc though, will the setup.py have the right links?

**Comment by maranas** [comment]
As it is, I don't think adding this to pypi is a good idea; this was originally just an answer to a Quora question. anyone who wants to do that is welcome to try, though; the only dependency is pyobjc.
